### ISSUE TITLE
Make as a tool to trial.

### ISSUE THREAD

**Issue by mhaley-miovision** [Miovision/tech-radar#2]
We have been using make on the coresystems team with great success.  I am very happy with how well the tool works in closing some of the gaps our current tooling has.  Thoughts on including that as a tool for others to start picking up?

Things I like about make:
- Dependencies between tasks are clear
- Includes make it easy to share/re-use code
- Parallel builds let you easily manage many tasks
- Lots of awesome built-ins like tab completion and templating.
- Provides a single entrypoint for you project that is easy to follow.

**Comment by awesometown** [comment]
I feel like I'd like to see it adopted more widely, or at least some indication that other teams are interested in it. We're not using it all the widely in coresystems yet; are any other teams using it (and would they endorse it)?

The same critique can be levelled at other items: Istio, for example, isn't actually in use anywhere, but there's a vague plan that we want to roll out _something_ in the service mesh space across multiple teams, and it's the leading contender. 

Also, I'm annoyed that none of the makefiles ever work on my mac :P

**Comment by mhaley-miovision** [comment]
I feel like other teams do you them.  I am sure the hardware team is using them. I also bet that coreip is also using them in their c builds.  Do others have thoughts here?

Overall I am very happy with how we have used make, so thought I would mention it and see what others thought about it.  I was going to point to terragrunt that other teams only use it where we have gone and set something up, but it's not even mentioned....

The fact that they don't work on your mac has nothing to do with make.  A similar batch file would also not work.  I think we have gotten better at that.

**Comment by awesometown** [comment]
@aachkar-miovision @dhillis-miovision @adewolfe-miovision @MikeLoder Thoughts?

**Comment by dhillis-miovision** [comment]
We use make for the smartlink.  I've used make for years.  It's certainly ubiquitous, but that doesn't make it great.  It has a few downsides that I've seen:

- Setting up proper incremental builds can require a lot of work.  
- Recursive builds get pretty weird.  I remember this article explains some of the ins and outs https://embeddedartistry.com/blog/2017/04/10/recursive-make-considered-harmful/
- So many footguns.  Make is full of unexpected behaviour that isn't intuitive.  Forgetting a .phony directive can lead to builds mysteriously not running some of the time.
- Various specs.  I think John's issue may be due to the fact there are multiple implementations of Make that aren't fully compatible with either other.  Does Mac bring in GNU Make or Standard Make?
- Lack of standardization. Every Makefile I've ever read has been different and weird in their own way.  The Smartlink make system looks nothing like buildroot which looks nothing like the SmartSense (which uses some cmake as well).

All that being said, there's a reason that Make has survived for 40+ years.  It does the trick, it's installed in some form on pretty much every machine.  Maybe there are some solid use cases where it's a good fit: C build system, build tools that have timestamped files for outputs, etc.

**Comment by aachkar-miovision** [comment]
The miocv repo uses cmake for building streamagent. I don't think we use make or cmake anywhere else.

**Comment by adewolfe-miovision** [comment]
I think I used make in university once...

tdo/qap/datalink are not using make anywhere as far as i know.

**Comment by MikeLoder** [comment]
I would agree to put make as trial. We use it all over the place in firmware. If someone is starting a new project, I personally would prefer cmake over make so trial is the right spot in my mind.

**Comment by awesometown** [comment]
>  I personally would prefer cmake over make so trial is the right spot in my mind.

If `cmake` would be preferable to `make`, that seems like more reason not to put `make` on the radar at all?

I'm still hesitant to put either on the radar as I don't have a clear sense of what we'd be trying to say by doing so. "Use Make in places where the obvious choice would be to use Make" isn't super useful; by the same token, we've got lots of other context-specific build tools (Gradle, MSBuild, Rake) that we haven't enumerated, and I think that's fine.

If there were a consensus that we should standardize on `cmake` over `make`, that might be something worth calling out.

**Comment by MikeLoder** [comment]
Thats fair, but context comes in to play. If we were starting a new C/C++ project I would get the team to use cmake as the starting point. However if your trying to build a quick system of dependencies, or a build script for multiple components. Make provides the dependency framework you would need to do something quickly.

**Comment by awesometown** [comment]
Keeping in mind that we don't want to overly-dilute the radar, I kind of feel like there isn't enough to say about `make` then that justifies its inclusion right now. It's a build tool that some people use when it's appropriate (but so are gradle, rake, cmake, etc.). There isn't a generalized behavior we want to drive ("make should be the first thing you consider for a build tool" or "use make instead of tool x").

If that changes (or someone writes up more generalized advice that people agree with) we could look at adding it into the next iteration.

**Comment by mhaley-miovision** [comment]
Sounds fair to me.  This issue at least made people aware that we are using it, so that's good enough for me.
